import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icon-logo.ico" />
      </Head>

      <main className={styles.main}>
        <div><h1>Forca</h1></div>
        <div>
          <Image src="/images/forca.png" alt="Imagem Forca" width={400} height={400} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://progtec-assistencia-tecnica.negocio.site"
          target="_blank"
          rel="noopener noreferrer"
        >
          Desenvolvido por{' '}
          <span className={styles.logo}>
            <Image src="/images/icon-logo.ico" alt="luizbarueri@gmail.com" width={32} height={32} />
          Luiz Amaro  
          </span>
        </a>
      </footer>
    </div>
  )
}
